---
- name: Ipfw validate
  ansible.builtin.command: ipfw -qfn /usr/local/etc/ipfw.txt
  tags: firewall

- name: Ipfw restart
  ansible.builtin.service:
    name: ipfw
    state: restarted
  tags: firewall

