---
- name: Create combined rules variable
  ansible.builtin.set_fact:
    _pf_rules_combined: "{{ pf_rules_global | default([]) }}"
  tags: pf

- name: Combine global and group rules
  when: pf_rules_group is defined
  ansible.builtin.set_fact:
    _pf_rules_combined: "{{ _pf_rules_combined + pf_rules_group }}"
  tags: pf

- name: Combine global and host rules
  when: pf_rules_host is defined
  ansible.builtin.set_fact:
    _pf_rules_combined: "{{ _pf_rules_combined + pf_rules_host }}"
  tags: pf

- name: Write pf.conf
  ansible.builtin.template:
    dest: /etc/pf.conf
    validate: 'pfctl -n -f %s'
    owner: root
    group: wheel
    mode: 0644
  tags: pf
  notify:
    - Pf reload
