---
- name: Create combined configs variable
  ansible.builtin.set_fact:
    freebsd_combined_configs: "{{ freebsd_configs_global | default({}) }}"
  tags: config

- name: Combine global and group configs
  when: freebsd_configs_group is defined
  ansible.builtin.set_fact:
    freebsd_combined_configs: "{{ freebsd_combined_configs | combine(freebsd_configs_group, recursive=True) }}"
  tags: config

- name: Combine global and host configs
  when: freebsd_configs_host is defined
  ansible.builtin.set_fact:
    freebsd_combined_configs: "{{ freebsd_combined_configs | combine(freebsd_configs_host, recursive=True) }}"
  tags: config

- name: Drop config files
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('wheel') }}"
    mode: "{{ item.mode | default('0644') }}"
  when: "'format' not in item"
  loop: "{{ freebsd_combined_configs.values() }}"
  tags: config
