---
- name: Ensure sysctls are set - global
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set | default(True)}}"
  loop: "{{ freebsd_sysctl_global | default([]) }}"
  tags: sysctl

- name: Ensure sysctls are set - group
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set | default(True)}}"
  loop: "{{ freebsd_sysctl_group | default([]) }}"
  tags: sysctl

- name: Ensure sysctls are set - host
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set | default(True)}}"
  loop: "{{ freebsd_sysctl_host | default([]) }}"
  tags: sysctl
