---
on:
  release:
    types:
      - published
    secrets:
      GALAXY_API_KEY:
        required: true
jobs:
  deploy:
    permissions:
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build collection
        id: build-collection
        uses: ansible-community/github-action-build-collection@main

      - run: ls -lR

      - run: env

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ steps.build-collection.outputs.artifact-filename }}

      - name: ansible-publish-action
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.GALAXY }}
